---
title: "Kaggle - House Prices"
output:
  html_document: default
  html_notebook: default
---

Predict sales prices and practice feature engineering, RFs, and gradient boosting

```{r}
rm(list=ls())
PROJ_PATH <- '~/Documents/kaggle/house_prices'

load(file.path(PROJ_PATH, 'data/house_prices.Rdata'))

# Plotting functions
hist2 <- function(..., breaks=30, col='darkgray', xlab=NULL){
  hist(..., breaks=breaks, col=col, border=col, xlab=xlab)
}

barplot2 <- function(..., col='darkgray', xlab=NULL){
  barplot(..., col=col, border=col, horiz=TRUE)
}

plot2 <- function(..., col=adjustcolor('gray30', alpha.f=0.2), bty='n'){
  plot(..., col=col, bty=bty)
}
```

Data description
```{r}
dim(train)
```

```{r}
names(train)
```

 Histograms of numeric variables
```{r, fig.width=9, fig.height=1.8}
par(mar=c(3,3,3,3))
par(mfrow = c(1, 4))

for (ni in num_idx){
  hist2(train[[ni]], main=nm[ni])
}

```
```{r}
hist2(train[['SalePrice']], main='SalePrice')
```

Frequencies of categorical variables
```{r, fig.width=9, fig.height=2}
par(las=2)
par(mar=c(3,4,3,3))
par(mfrow = c(1, 4))

for (ci in cat_idx){
  barplot2(table(train[[ci]], useNA='ifany'), main=nm[ci])
}
```

Missingness of variables (only those with any values missing)
```{r, fig.width=6, fig.height=3}
missing_perc <- sort(sapply(train, function(x) sum(is.na(x)) / length(x)))

par(las=2)
par(mar=c(3,7,2,2))
barplot2(missing_perc[missing_perc>0],
         cex.names=0.6, cex.axis=0.6, xlim=c(0,1),
         main='Missingness')
```

Relation of each variable to price
```{r, fig.width=9, fig.height=1.8}

par(mar=c(3,3,3,3))
par(mfrow = c(1, 4))

for (ni in num_idx){
  plot2(train[,c(nm[ni], 'SalePrice'),],
       main=nm[ni], ylim=range(train$SalePrice))
}
```
```{r, fig.width=9, fig.height=1.8}

par(mar=c(3,3,3,3))
par(mfrow = c(1, 4))

for (ni in cat_idx){
  plot2(factor(train[[ni]]), train$SalePrice,
       main=nm[ni], ylim=range(train$SalePrice),
       frame=FALSE)
}
```

Top correlated numeric variables (pairwise-complete observations)
```{r, fig.width=6}
cor_mat <- cor(train[,num_idx], use='pairwise.complete')
cor_mat[!upper.tri(cor_mat)] <- NA

not_na_mat <- !is.na(as.matrix(train[,num_idx]))
pairwise_completeness <- t(not_na_mat) %*% not_na_mat / nrow(train)

cor_df <- data.frame(x1=rep(colnames(cor_mat), each=ncol(cor_mat)),
                     x2=rep(colnames(cor_mat), times=ncol(cor_mat)),
                     cor=as.vector(cor_mat),
                     perc_complete=as.vector(pairwise_completeness))

cor_df <- cor_df[!is.na(cor_df$cor),]
cor_df <- cor_df[order(abs(cor_df$cor), decreasing=TRUE),]
knitr::kable(cor_df[abs(cor_df$cor) > 0.50,], row.names=FALSE)
```


